---
title: "p8105_hw3_yw3236"
output: github_document
author: "Yishan Wang"
date: 2018-10-15
---

# Problem 1

```{r set up library, include = FALSE}
library(tidyverse)
library(dplyr)
```

```{r}
devtools::install_github("p8105/p8105.datasets")
```

```{r}
library(p8105.datasets)
data(brfss_smart2010) 
```

### Clean Data

* Format the data to use appropriate variable names
* Focus on the “Overall Health” topic
* Include only responses from “Excellent” to “Poor”
* Organize responses as a factor taking levels ordered from “Excellent” to “Poor”

```{r}
formated_brfss_smart2010 = brfss_smart2010 %>%
  janitor::clean_names() %>%
  rename(., state = locationabbr, county = locationdesc) %>%
  filter(., topic == "Overall Health") %>%
  filter(., response == "Excellent" | response == "Very good" | response == "Good" | response == "Fair" | response == "Poor") %>%
  mutate(., factor(response, levels = c("Excellent", "Very good", "Good", "Fair", "Poor")))

formated_brfss_smart2010
```

### Question 1

```{r}
formated_brfss_smart2010_2002 = formated_brfss_smart2010 %>%
  filter(., year == "2002") %>%
  select(., year, state, county) %>%
  unique(.) %>%
  group_by(state) %>%
  summarize(n = n())
```

In 2002, CT, FL, NC were observed at 7 locations.

